n = input('Digite algo: ')
print(f'O tipo primitivo desse valor é: {type(n)}')
print(f'Só tem espaços? {n.isspace()}')
print(f'É um número? {n.isnumeric()}')
print(f'É alfabético? {n.isalpha()}')
print(f'É alfanumérico? {n.isalnum()}')
print(f'Está somente em maiuscula? {n.isupper()}')
print(f'Está somente em minúscula? {n.islower()}')
print(f'Está capitalizada? {n.istitle()}')